### ISSUE TITLE
Add support for redacting values

### ISSUE THREAD

**Issue by maxsz** [relistan/rubberneck#2]
Hey, great little library, I love it 👏
I just came across a usecase, where it would be awesome if the `rubberneck.NewPrinter` function would accept a third parameter, for example a `func(key string) bool`, that would allow redacting config values. For example passwords etc. 
What do you think?

**Comment by relistan** [comment]
Definitely would be nice to be able to filter out redacted values. That seems like a reasonable way to do it. It would change the public API, though, so an alternative would be a new constructor function named `NewPrinterWithKeyFilter` or something similar.

**Comment by maxsz** [comment]
Ok, cool. I'll work on a PR soon 👍
